# Generated by Django 5.2.4 on 2025-07-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('food_type', models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('both', 'Both')], max_length=10)),
                ('category', models.CharField(choices=[('dessert', 'Dessert'), ('full_course', 'Full Course'), ('other', 'Other')], default='other', max_length=20)),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
