# Generated by Django 5.2.4 on 2025-07-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Foodie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodspot',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='foodspot',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
